const animalsHardCopy = [
  {
    animalId: 1,
    animalName: "Tom",
    animalBio: "Je suis doux comme du miel",
    animalProfession: "coursier",
    animalAge: 5,
    animalIsreal: 0,
    animalMatch: 0,
    animalType: "chat",
  },
  {
    animalId: 2,
    animalName: "Rex",
    animalBio: "J’ai transformé mes rêves en vision et ma vision en réalité",
    animalProfession: "Archéologue",
    animalAge: 3,
    animalIsreal: 0,
    animalMatch: 0,
    animalType: "chien",
  },
  {
    animalId: 3,
    animalName: "Petit Tonerre",
    animalBio: "Entrepreneur. Globetrotter. Orateur motivant",
    animalProfession: "Agriculteur bio",
    animalAge: 8,
    animalIsreal: 0,
    animalMatch: 0,
    animalType: "cheval",
  },
  {
    animalId: 4,
    animalName: "Tom",
    animalBio: "Ne me faites pas perdre mon sang froid",
    animalProfession: "Pecheur",
    animalAge: 2,
    animalIsreal: 0,
    animalMatch: 0,
    animalType: "requin",
  },
  {
    animalId: 5,
    animalName: "Titi",
    animalBio: "Je m’engage auprès de la NASA parce que je suis une étoile",
    animalProfession: "Nettoyeur de réverbères",
    animalAge: 5,
    animalIsreal: 0,
    animalMatch: 0,
    animalType: "oiseau",
  },
  {
    animalId: 6,
    animalName: "Tom",
    animalBio: "Voyageur. Amoureux de livres. Obsédé par les tacos ",
    animalProfession: "Couveur d'oeuf",
    animalAge: 5,
    animalIsreal: 0,
    animalMatch: 0,
    animalType: "pingouin",
  },
  {
    animalId: 7,
    animalName: "Chantale",
    animalBio: "Mes exigences sont élevées… tout comme mes talons",
    animalProfession: "Escort-girl",
    animalAge: 4,
    animalIsreal: 0,
    animalMatch: 0,
    animalType: "lapin",
  },
  {
    animalId: 8,
    animalName: "Edwige",
    animalBio: "Si l’amour est dans l’air, pourquoi l’air est-il si pollué ?",
    animalProfession: "Veilleur de nuit",
    animalAge: 1,
    animalIsreal: 0,
    animalMatch: 0,
    animalType: "hibou",
  },
  {
    animalId: 10,
    animalName: "Jojo",
    animalBio: "L'amour est dans le pres",
    animalProfession: "Dresseur de phoque",
    animalAge: 1,
    animalIsreal: 1,
    animalMatch: 0,
    animalType: "lapin",
  },
];

export default animalsHardCopy;
